#!/usr/bin/env python3
"""
Generate MoonBit entities.mbt from WHATWG entities.json

Source: https://html.spec.whatwg.org/entities.json
"""

import json
import urllib.request
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
OUTPUT_FILE = SCRIPT_DIR.parent / "src" / "entities.mbt"
ENTITIES_URL = "https://html.spec.whatwg.org/entities.json"

LICENSE_HEADER = """// ============================================================================
// AUTO-GENERATED FILE - DO NOT MODIFY MANUALLY
// Generated by: scripts/generate_entities.py
// Source: https://html.spec.whatwg.org/entities.json
// ============================================================================

// Copyright 2025 International Digital Economy Academy
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

"""


def escape_moonbit_string(s: str) -> str:
    """Escape a string for MoonBit string literal."""
    result = []
    for c in s:
        code = ord(c)
        if c == '\\':
            result.append('\\\\')
        elif c == '"':
            result.append('\\"')
        elif c == '\n':
            result.append('\\n')
        elif c == '\t':
            result.append('\\t')
        elif c == '\r':
            result.append('\\r')
        else:
            result.append(c)
    return ''.join(result)


def main():
    print(f"Downloading entities from {ENTITIES_URL}...")
    with urllib.request.urlopen(ENTITIES_URL) as response:
        entities = json.loads(response.read().decode('utf-8'))

    print(f"Found {len(entities)} entities")

    # Use lazy-loaded Map to avoid OOM at module init
    lines = [LICENSE_HEADER]
    lines.append("///|")
    lines.append("/// WHATWG HTML5 Named Character References (2,231 entities)")
    lines.append("/// https://html.spec.whatwg.org/multipage/named-characters.html")
    lines.append("///")
    lines.append("/// Uses lazy loading to avoid OOM during module initialization.")
    lines.append("")
    lines.append("///|")
    lines.append("/// Lazy-initialized entity map")
    lines.append("let entity_map : Ref[Map[String, Array[Int]]?] = { val: None }")
    lines.append("")
    lines.append("///|")
    lines.append("/// Initialize the entity map (called lazily on first lookup)")
    lines.append("fn init_entities() -> Map[String, Array[Int]] {")
    lines.append("  let m : Map[String, Array[Int]] = Map::new()")

    for entity_name, data in sorted(entities.items()):
        # Remove leading & from entity name
        name = entity_name[1:]  # Remove &
        codepoints = data['codepoints']
        cps_str = ", ".join(str(cp) for cp in codepoints)
        escaped_name = escape_moonbit_string(name)
        lines.append(f'  m["{escaped_name}"] = [{cps_str}]')

    lines.append("  m")
    lines.append("}")
    lines.append("")
    lines.append("///|")
    lines.append("/// Get the entity map, initializing lazily if needed")
    lines.append("fn get_entities() -> Map[String, Array[Int]] {")
    lines.append("  match entity_map.val {")
    lines.append("    Some(m) => m")
    lines.append("    None => {")
    lines.append("      let m = init_entities()")
    lines.append("      entity_map.val = Some(m)")
    lines.append("      m")
    lines.append("    }")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    lines.append("///|")
    lines.append("/// Lookup a named character reference (without the leading &)")
    lines.append("/// Returns array of codepoints if found")
    lines.append("pub fn lookup_entity(name : String) -> Array[Int]? {")
    lines.append("  get_entities().get(name)")
    lines.append("}")
    lines.append("")

    output = "\n".join(lines)
    OUTPUT_FILE.write_text(output, encoding='utf-8')
    print(f"Written to {OUTPUT_FILE}")
    print(f"Generated {len(entities)} entity entries")


if __name__ == "__main__":
    main()
